// Generated by CoffeeScript 1.6.3
var Scene,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Scene = (function() {
  var HEIGHT, WIDTH;

  WIDTH = HEIGHT = 500;

  function Scene(options) {
    this.update = __bind(this.update, this);
    this.renderer = new THREE.WebGLRenderer({
      preserveDrawingBuffer: true,
      antialias: true
    });
    this.renderer.setSize(options.width, options.height);
    this.scene = new THREE.Scene();
    this.camera = new THREE.OrthographicCamera(WIDTH / -2, WIDTH / 2, HEIGHT / 2, HEIGHT / -2, -5000, 5000);
    this.frameLength = 1000 / 30;
  }

  Scene.prototype.update = function() {
    var _this = this;
    console.log('update');
    setTimeout((function() {
      requestAnimationFrame(_this.update);
      return null;
    }), this.frameLength);
    return null;
  };

  return Scene;

})();
